name: "Grace project - Rate"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 9 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_project_update_rate:
    name: rate project - update home rate
    runs-on: ubuntu-latest

    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          PROJECT_NAME: rate project
        run: |
          echo $MY_VAR $PROJECT_NAME.

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: run script
        # run: bash ./wh.sh \
        run: python ./_posts/00CodeNote/project/rate_tracker/rate_tracker.py

      - name: Commit and push changes
        run: |
          git config --global user.name "grace"
          git config --global user.email "lgraceye@hotmail.com"
          git pull origin master
          git add .
          git commit -m "Auto CI Job - update home rate img"
          git push
