name: 'Grace project - Apt'

on:
  push:
    branches:
      - master
  #   paths-ignore:
  #     - .gitignore
  #     - README.md
  #     - LICENSE
  # schedule:
  #   - cron: '0 21 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_project_csv_builder:
    name: project webscrap_apt create csv
    # runs-on: macOS-latest
    runs-on: ubuntu-latest

    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          PROJECT_NAME: webscrap_apt
        run: |
          echo $MY_VAR $PROJECT_NAME.

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: run apt project script
        # run: bash ./wh.sh \
        run: python ./_posts/00CodeNote/project/webscrap_apt/play.py -t all

      # - name: Install Python dependencies
      #   run: python -m pip install -r ./_posts/00CodeNote/project/webscrap_apt/requirements.txt

      # - name: run img player
      #   run: python ./_posts/00CodeNote/project/webscrap_apt/img_play.py

      - name: Commit and push changes
        run: |
          git config --global user.name "grace"
          git config --global user.email "lgraceye@hotmail.com"
          git pull origin master
          git add .
          git commit -m "Auto updating csv to repo"
          git push

  run_project_img_builder:
    name: project webscrap_apt print img
    # runs-on: macOS-latest
    runs-on: ubuntu-latest
    needs: run_project_csv_builder

    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          PROJECT_NAME: webscrap_apt
        run: |
          echo $MY_VAR $PROJECT_NAME.

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Install Python dependencies
        run: python -m pip install -r ./_posts/00CodeNote/project/webscrap_apt/requirements.txt

      - name: run img player
        run: python ./_posts/00CodeNote/project/webscrap_apt/img_play.py

      - name: Commit and push changes
        run: |
          git config --global user.name "grace"
          git config --global user.email "lgraceye@hotmail.com"
          # git pull origin master
          git add .
          git commit -m "Auto updating img to repo"
          git push
